# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
